services:
  postgres:
    image: postgres:16
    container_name: aurora-postgres
    environment:
      POSTGRES_DB: aurora_db
      POSTGRES_USER: aurora_user
      POSTGRES_PASSWORD: aurora_pass
    ports:
      - "5434:5432"
    volumes:
      - aurora_data:/var/lib/postgresql/data
      - ../../db/init/cria_banco.sql:/docker-entrypoint-initdb.d/cria_banco.sql
    restart: unless-stopped

volumes:
  aurora_data:
